version: "3"
services:
  poll:
    build: ./poll/
    ports:
      - "5000:80"
    networks:
      - poll-tier
    environment:
      - PORT: 80

  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - poll-tier
      - back-tier
    restart: always

  worker:
    build: ./worker/
    networks:
      - back-tier

  db:
    image: postgres:15.2
    networks:
      - result-tier
      - back-tier
    volumes:
      - db-data:/var/lib/db
    environment:
      - POSTGRESHOST: /var/lib/db

  result:
    build: ./result/
    ports:
      - "5001:80"
    networks:
      - result-tier
    environment:
      - PORT: 80

networks:
  poll-tier:
    driver: bridge
  result-tier:
    driver: bridge
  back-tier:
    driver: bridge

volumes:
  db-data:
    driver: local

#depends on